### ISSUE TITLE
Manage User Accounts

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-compass#42]
### Motivation
We somehow need to manage access to the tool. Can we use the default CRUD back end? This will suffice for the beginning. Who is going to manage access in the long term?

### User Story
As a project admin I want to create users in the Django back end and assign a user role.

### Proposed Solution
- We can use the Django back end for the MVP.
- We need to have roles (board member, counselor, organization representative).
- The password reset e-mail notification should work to immediately trigger it for new user accounts.

### Alternatives
- None

**Comment by timobrembeck** [comment]
I think we can definitely start with the default Django admin interface, but I would suggest to at least add a custom user model (see [docs](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#substituting-a-custom-user-model)) to provide the option to customize it later on (otherwise, migrations of the user model in mid-project are a bit complicated).

**Comment by charludo** [comment]
> I think we can definitely start with the default Django admin interface, but I would suggest to at least add a custom user model (see [docs](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#substituting-a-custom-user-model)) to provide the option to customize it later on (otherwise, migrations of the user model in mid-project are a bit complicated).

Since this is already done, can we move this to the backlog?
