### ISSUE TITLE
Make logging output colored

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-compass#54]
### Describe the Bug

The logger prints events of all severities without color. We would like to color different severities differently for easier readability.

### Steps to Reproduce

1. Run the project
2. See black-and-white output

### Expected Behavior

Colored output

### Actual Behavior

Non-colored output

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```
</details>

**Comment by timobrembeck** [comment]
This is not a bug, since the default logging output of Django is just black and white.
The colored output of integreat-cms was achieved by a [custom logging formatter](https://github.com/digitalfabrik/integreat-cms/blob/af1157fa59eda3073c8b0329931d98a803cecd1b/integreat_cms/core/logging_formatter.py#L4-L35), which could be copied + pasted for this project.
