### ISSUE TITLE
Make offer details accessible from applications view

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-compass#87]
### Motivation

Board members should be able to quickly look at offer details.

### User Story

As a board member, I want to have easy access to all details about an offer when deciding on how to vote.

### Proposed Solution

Once #61 and #75 are merged, largely copy the popup introduced in #75, minus the eventual reporting and commenting functionalities, as well as the ratings by integration specialists.

### Alternatives

Make something new

### Additional Context

Blocked by:
- [x] #75 

### Screenshots

![image](https://github.com/digitalfabrik/integreat-compass/assets/47758554/b9ce2a05-80d5-47a3-873e-6f3d796650d4)

**Comment by JoeyStk** [comment]
Does someone have an opinion on which would be the best way to implement this?

Since copying large portions of the code and only changing it in small ways didn't seem DRY to me, I therefore attempted to also include the offer details overlay and hand over some arguments to the offer-details template. First argument would have been to change offer_version to offer. With this it was at least possible to open the according overlay. However the overlay is empty because for the applications of course there is no public version. I only had dirty solutions to get rid of the public_version and instead access the latest version (handing over another parameter public_version as a boolean. If it's True show the public_version if it's False access the latest version). I'm not really satisfied with this solution and therefore wanted to hear your ideas on this :) Ping to: @svenseeberg and @charludo
